### ISSUE TITLE
Woflictl seg faults if non existent command options is added

### ISSUE THREAD

**Issue by strongjz** [wolfi-dev/wolfictl#239]
Built wolfictl from source at 0e133a790f792c2877c1d8c674d5473f516afffc 

````bash
 wolfictl lint yam
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x127560a]

goroutine 1 [running]:
github.com/wolfi-dev/wolfictl/pkg/melange.ReadAllPackagesFromRepo.func1({0x7ffe8439b1c3, 0x3}, {0x0?, 0x0?}, {0xc00087e730?, 0x4291a5?})
	/home/strongjz/Documents/code/go/src/github.com/wolfi/wolfictl/pkg/melange/melange.go:71 +0x4a
path/filepath.Walk({0x7ffe8439b1c3, 0x3}, 0xc00087e820)
	/usr/local/bin/go/src/path/filepath/path.go:518 +0x50
github.com/wolfi-dev/wolfictl/pkg/melange.ReadAllPackagesFromRepo({0x7ffe8439b1c3, 0x3})
	/home/strongjz/Documents/code/go/src/github.com/wolfi/wolfictl/pkg/melange/melange.go:70 +0xc8
github.com/wolfi-dev/wolfictl/pkg/lint.(*Linter).Lint(0xc0009a27d0)
	/home/strongjz/Documents/code/go/src/github.com/wolfi/wolfictl/pkg/lint/linter.go:49 +0x67
github.com/wolfi-dev/wolfictl/pkg/cli.lintOptions.LintCmd({{0xc0002b22d0, 0x1, 0x1}, 0x0, 0x0, {0x409b470, 0x0, 0x0}})
	/home/strongjz/Documents/code/go/src/github.com/wolfi/wolfictl/pkg/cli/lint.go:48 +0xac
github.com/wolfi-dev/wolfictl/pkg/cli.Lint.func1(0xc00099cc00?, {0xc0002b22d0?, 0x1?, 0x1?})
	/home/strongjz/Documents/code/go/src/github.com/wolfi/wolfictl/pkg/cli/lint.go:29 +0x95
github.com/spf13/cobra.(*Command).execute(0xc00099cc00, {0xc0002b2290, 0x1, 0x1})
	/home/strongjz/Documents/code/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc00099c300)
	/home/strongjz/Documents/code/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/strongjz/Documents/code/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/home/strongjz/Documents/code/go/src/github.com/wolfi/wolfictl/main.go:10 +0x1e
````

**Comment by Dentrax** [comment]
Couldn't able to reproduce at that commit:

```bash
$ go run . lint yam

FATA[0000] error during command execution: unable to load yam config: unable to read yam config: open .yam.yaml: no such file or directory
exit status 1
```
